spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/club
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #테이블 재생성
#      ddl-auto: update #테이블 유지
    properties:
      hibernate:
        format_sql: true

# 로그 색상나오게 출력
  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug
  com.club.badminton: trace

# 세션을 url이 아닌 쿠키를 사용하도록 강제함. (로그인시 jsessionid가 url에 들어가면서 404 에러나는 것을 방지함)
server:
  servlet:
    session:
      tracking-modes: cookie

file:
  upload-dir: C:/club-file-upload/
