-- 모든 테이블 각각 조회
SELECT * FROM ATTACHMENT;
SELECT * FROM BUDGET;
SELECT * FROM CLUB;
SELECT * FROM CLUB_CATEGORY;
SELECT * FROM CLUB_MEMBER;
SELECT * FROM COMMENTS;
SELECT * FROM MEMBER;
SELECT * FROM POST;
SELECT * FROM SCHEDULE;
SELECT * FROM TRANSACTIONS;