-- 모든 테이블 각각 조회
SELECT * FROM BOARD;
SELECT * FROM BOARD_FILE;
SELECT * FROM CATEGORY;
SELECT * FROM CLUB;
SELECT * FROM CLUB_CATEGORY;
SELECT * FROM CLUB_MEMBER;
SELECT * FROM COMMENT;
SELECT * FROM MEMBER;
SELECT * FROM POST;
SELECT * FROM ROLE;