SELECT * FROM MEMBER;

-- SELECT * FROM SI_DO;
-- SELECT * FROM GU_GUN;
-- SELECT * FROM DONG_RI;

SELECT * FROM CLUB_MEMBER;
SELECT * FROM CLUB;
SELECT * FROM CLUB_CATEGORY;

SELECT * FROM BUDGET;
SELECT * FROM TRANSACTIONS;

SELECT * FROM POST;
SELECT * FROM ATTACHMENT;
SELECT * FROM COMMENTS;

SELECT * FROM SCHEDULE;
