-- H2 DB 모든 테이블 지우기
-- drop all objects;

-- 모든 테이블 조회
SELECT * FROM ADDRESS;
SELECT * FROM ADDRESS_LV1;
SELECT * FROM ADDRESS_LV2;
SELECT * FROM ADDRESS_LV3;
SELECT * FROM ATTACHMENT;
SELECT * FROM BUDGET;
SELECT * FROM CLUB;
SELECT * FROM CLUB_MEMBER;
SELECT * FROM COMMENTS;
SELECT * FROM MEMBER;
SELECT * FROM POST;
SELECT * FROM SCHEDULE;
SELECT * FROM TRANSACTIONS;